[default]
description = "Default permissions for the plugin"
permissions = [
  "allow-get-product-details",
  "allow-launch-purchase-flow",
  "allow-query-purchases",
  "allow-ping",
  "allow-registerListener",
  "allow-remove-listener",
  "allow-unregister-listener",
]
